### PR TITLE
Restructured fetching logic to make it clearer

### LINKED ISSUE #20: How to disable `whereToFetchOnline` and `changeButtonProvider` ?
```
UnhandledPromiseRejectionWarning: TypeError: filterWrapper is not iterable
    at Object.exports.parseFilters (D:\Tools\vlc-rpc\node_modules\ytsr\lib\utils.js:23:29)
    at module.exports (D:\Tools\vlc-rpc\node_modules\ytsr\lib\main.js:60:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.exports (D:\Tools\vlc-rpc\src\rpc\format.js:124:22)
    at async D:\Tools\vlc-rpc\src\rpc\client.js:24:26
```
It shows a lot of these when changing the track.

### PR DESCRIPTION
**Pull request by sdasda7777**
The restructuring not only makes it easier to debug and extend, but also fixes #20 due to not calling the Youtube library unless explicitly desired by the user.

### CODE REVIEW

**Comment by sdasda7777** [comment]
@GreenDiscord Hi, could you take a look at this please? 😄

**Comment by GreenDiscord** [comment]
For sure, as always, is it tested to be working?

**Comment by sdasda7777** [comment]
It works for me, but I honestly still don't understand some parts of the program, so I might be missing something that I just didn't think to test 😅 It also doesn't check Spotify as a backup in case Apple failed to find anything anymore, but I think that was sort of misleading to do anyways 😅

**Comment by sdasda7777** [comment]
Actually, it might be good idea to ask @Choomai if it solves their issue before merging 😅

**Comment by GreenDiscord** [comment]
> It works for me, but I honestly still don't understand some parts of the program, so I might be missing something that I just didn't think to test 😅 It also doesn't check Spotify as a backup in case Apple failed to find anything anymore, but I think that was sort of misleading to do anyways 😅

Only reason I had the option to choose is if spotify had different album work vice versa.

**Comment by sdasda7777** [comment]
Ah, I see, that makes sense 😅  I'll look into how to best keep the functionality, then 😅

**Comment by sdasda7777** [comment]
@GreenDiscord Now it should be checking other sources if the preferred ones fail. I also added try-catch-finally around the Youtube fetching code, so now it won't crash anymore, just print the error.
By the way, would you happen to know what the error @Choomai is getting (it's posted at #20) might mean? 😅

**Comment by sdasda7777** [comment]
@GreenDiscord It appears to be working as intended with this last commit. Do you have any concerns about the new code? 😄

**Comment by GreenDiscord** [comment]
This all good now?

**Pull request merged**
